### ISSUE TITLE
Broken world visualization; parts of buildings misplaced  

### ISSUE THREAD

**Issue by james-salafatinos** [dennisdev/rs-map-viewer#3]
Things are offset seemingly at random...

**Comment by dennisdev** [comment]
Hello, could you provide a screenshot or link where it is broken?

**Comment by james-salafatinos** [comment]
![image](https://github.com/dennisdev/rs-map-viewer/assets/47095723/d0c61727-b51d-4eab-9198-659f929779ab)
![image](https://github.com/dennisdev/rs-map-viewer/assets/47095723/4bfdd052-a8cf-4332-b09c-0368324330f7)

**Comment by dennisdev** [comment]
Is it also broken at https://osrs.world for you?

**Comment by james-salafatinos** [comment]
Awesome! Will check it out. You the man

Sent via my phone
________________________________
